import math
count = -1
for count, line in enumerate(open("muons.txt",'r')):
    pass
count += 1
realCount = count//5

file = open("muons.txt","r")
file2 = open("Calculation Result.txt","w")

for i in range(0,realCount):
    a= file.readline()
    c= file.readline()
    str1 = file.readline()
    str2=file.readline()
    b= file.readline()

    string1 = str1.split()
    string2 = str2.split()

    pt1=eval(string1[2])# "transverse momentum"
    phi1=eval(string1[3])#"angle in the x-y plane"
    eta1=eval(string1[4])#"pseudorapidity, which is another form of the angle from the z-axis")
    mass1=eval(string1[5])


    pt2=eval(string2[2])# "transverse momentum"
    phi2=eval(string2[3])#"angle in the x-y plane"
    eta2=eval(string2[3])#"pseudorapidity, which is another form of the angle from the z-axis")
    mass2=eval(string2[4])

    p1=pt1/(math.cos(eta1))
    px1=pt1*(math.cos(phi1))
    py1=pt1*(math.sin(phi1))
    pz1=pt1*(math.tan(eta1))
    energy1= math.sqrt(mass1**2 + p1**2)

    p2=pt2/(math.cos(eta2))
    px2=pt2*(math.cos(phi2))
    py2=pt2*(math.sin(phi2))
    pz2=pt2*(math.tan(eta2))
    energy2= math.sqrt(mass2**2 + p2**2)

    mFinal = math.sqrt((energy1+energy2)**2 + (px1+px2)**2 + (py1+p2)**2 + (pz1+pz2)**2 +(energy1/299792458+energy2/299792458)**2)

    finalFantasy = str(mFinal)
    file2.write(a) 
    file2.write(c)
    file2.write("Invariant Mass: "+finalFantasy)
    file2.write("\n\n")

file.close()
file2.close()
